name: eeg
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pytorch::pytorch=2.7.1
  - pytorch::torchvision=0.22.1
  - scipy=1.15.3
  - numpy=2.2.6
  - pyyaml=6.0.3
  - pillow=12.1.1
  - tqdm=4.67.3
  - pip:
    - open_clip_torch==3.3.0