#!/bin/bash
# Package the project for reproducible distribution
# This creates a tarball containing all files needed to reproduce results

set -e
PROJECT_DIR="/hpc2hdd/JH_DATA/jhai_data/dsaa2012_031/project_codex"
BACKUP_DIR="/hpc2hdd/JH_DATA/jhai_data/dsaa2012_031"
ARCHIVE_NAME="project_codex_reproduce_$(date +%Y%m%d).tar.gz"

echo "Creating reproducible package: $ARCHIVE_NAME"
echo "This may take a while..."

cd "$BACKUP_DIR"

# Create a manifest of what we're including
MANIFEST=$(mktemp)

cat > "$MANIFEST" << 'MANIFEST_HEADER'
# Reproducible Package Manifest
# Generated: $(date)
#
# Contents:
# 1. Code, configs, scripts (~7MB)
# 2. Pre-computed test logits (~20KB × 80 files)
# 3. Trained model checkpoints (best.pt only, ~5GB total)
# 4. Feature caches (~886MB)
# 5. EEG test data (~486MB)
# 6. Ensemble results and optimization results
# 7. Documentation (README, pipeline説明.md, reproduce_ensemble.sh)
MANIFEST_HEADER

echo "Step 1/7: Collecting code and configs..."
CODE_FILES=(
    eeg_cogcappro/*.py
    configs/*.yaml
    scripts/*.py
    slurm/*.sh
    reproduce_ensemble.sh
    README.md
    pipeline*.md
    environment.yml
)

echo "Step 2/7: Collecting test logits (needed for ensemble reproduction)..."
LOGITS_PATTERN="results/deep_*_test_tta5.logits.pt"

echo "Step 3/7: Collecting trained checkpoints (best.pt only, no last.pt or metrics.json)..."
# We only include best.pt files to save space

echo "Step 4/7: Collecting feature caches..."
CACHE_FILES=(
    cache/features_vitl_real.pt
    cache/features_vitl.pt
    cache/features_multi.pt
)

echo "Step 5/7: Collecting EEG test data..."
EEG_FILES=(
    image-eeg-data/test.pt
)

echo "Step 6/7: Collecting ensemble results..."
ENSEMBLE_FILES=(
    results/ensemble_eval_opt9mod/*
    results/grid_search_results.json
    results/reproduce_final  # will be generated by reproduce_ensemble.sh
)

echo "Step 7/7: Creating archive..."

# Build the tar command dynamically
TAR_FILES=""

# Code and configs
for pattern in "${CODE_FILES[@]}"; do
    TAR_FILES="$TAR_FILES project_codex/$pattern"
done

# Test logits (only test_tta5, not train or other splits)
TAR_FILES="$TAR_FILES project_codex/results/deep_*_test_tta5.logits.pt"

# Checkpoints (best.pt only)
for dir in project_codex/runs/*/; do
    if [ -f "${dir}best.pt" ]; then
        TAR_FILES="$TAR_FILES ${dir}best.pt"
    fi
done

# Feature caches
for f in "${CACHE_FILES[@]}"; do
    if [ -f "project_codex/$f" ]; then
        TAR_FILES="$TAR_FILES project_codex/$f"
    fi
done

# EEG test data (not train - too large, can regenerate)
for f in "${EEG_FILES[@]}"; do
    if [ -f "project_codex/$f" ]; then
        TAR_FILES="$TAR_FILES project_codex/$f"
    fi
done

# Ensemble results
TAR_FILES="$TAR_FILES project_codex/results/ensemble_eval_opt9mod"
TAR_FILES="$TAR_FILES project_codex/results/grid_search_results.json"

# Donation letter / important JSON results
TAR_FILES="$TAR_FILES project_codex/results/atms_multimodal_final*.json"

# Actually create the archive using find to handle glob patterns properly
echo "Creating tarball (this may take 10-20 minutes)..."

# Use tar with explicit file list
(
    # Code
    find project_codex/eeg_cogcappro -name "*.py" -print0
    find project_codex/configs -name "*.yaml" -print0
    find project_codex/scripts -name "*.py" -print0
    find project_codex/slurm -name "*.sh" -print0

    # Documentation
    echo -e "project_codex/reproduce_ensemble.sh\0project_codex/README.md\0project_codex/environment.yml\0"
    find project_codex -maxdepth 1 -name "pipeline*.md" -print0

    # Test logits
    find project_codex/results -name "*_test_tta5.logits.pt" -print0

    # Checkpoints (best.pt only)
    find project_codex/runs -name "best.pt" -print0

    # Feature caches
    find project_codex/cache -name "*.pt" -print0

    # EEG test data
    echo -e "project_codex/image-eeg-data/test.pt\0"

    # Ensemble results
    find project_codex/results/ensemble_eval_opt9mod -print0
    echo -e "project_codex/results/grid_search_results.json\0"
    find project_codex/results -name "atms_multimodal_final*.json" -print0
) | tar -czf "$ARCHIVE_NAME" --null -T -

SIZE=$(du -sh "$ARCHIVE_NAME" | cut -f1)
echo ""
echo "============================================"
echo "Archive created: $BACKUP_DIR/$ARCHIVE_NAME"
echo "Size: $SIZE"
echo "============================================"
echo ""
echo "To extract and reproduce:"
echo "  tar -xzf $ARCHIVE_NAME"
echo "  cd project_codex"
echo "  bash reproduce_ensemble.sh"
echo ""

rm -f "$MANIFEST"